region = "eu-central-1"
vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avail_zone = "eu-central-1a"
env_prefix = "dev"
my_ip = "***.***.***.**/32"
instance_type = "t2.micro"
public_ssh_key_location = "~/.ssh/id_rsa.pub"
